.TH "BallManager.h" 3 "Fri Mar 21 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BallManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'TileSimulator\&.h'\fP
.br
\fC#include 'Ball\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBallManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
