.TH "BallManager" 3 "Wed Apr 2 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BallManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BallManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBallManager\fP (\fBTileSimulator\fP *\fBsim\fP)"
.br
.ti -1c
.RI "virtual \fB~BallManager\fP ()"
.br
.ti -1c
.RI "bool \fBinitBallManager\fP ()"
.br
.ti -1c
.RI "void \fBinitMultiplayer\fP (int nPlayers)"
.br
.ti -1c
.RI "void \fBsetGlobalBall\fP (\fBBall\fP *ball)"
.br
.ti -1c
.RI "void \fBsetPlayerBall\fP (\fBBall\fP *ball, int idx)"
.br
.ti -1c
.RI "\fBBall\fP * \fBaddBall\fP (Ogre::SceneNode *n, int x, int y, int z, int r)"
.br
.ti -1c
.RI "\fBBall\fP * \fBaddMainBall\fP (Ogre::SceneNode *n, int x, int y, int z, int r)"
.br
.ti -1c
.RI "void \fBenableGravity\fP ()"
.br
.ti -1c
.RI "void \fBremoveBall\fP (\fBBall\fP *rmBall)"
.br
.ti -1c
.RI "void \fBremoveGlobalBall\fP ()"
.br
.ti -1c
.RI "void \fBremovePlayerBall\fP (int idx)"
.br
.ti -1c
.RI "bool \fBisGlobalBall\fP ()"
.br
.ti -1c
.RI "bool \fBisPlayerBall\fP (int idx)"
.br
.ti -1c
.RI "void \fBclearBalls\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberBallCollisions\fP ()"
.br
.ti -1c
.RI "\fBTileSimulator\fP * \fBgetSimulator\fP ()"
.br
.ti -1c
.RI "bool \fBcheckCollisions\fP (btRigidBody *aTile, void *body0, void *body1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBall\fP * \fBglobalBall\fP"
.br
.ti -1c
.RI "std::vector< \fBBall\fP * > \fBplayerBalls\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBBall\fP * > \fBballList\fP"
.br
.ti -1c
.RI "std::vector< \fBBall\fP * > \fBmainBalls\fP"
.br
.ti -1c
.RI "std::vector< bool > \fBplayerBallsActive\fP"
.br
.ti -1c
.RI "\fBTileSimulator\fP * \fBsim\fP"
.br
.ti -1c
.RI "bool \fBglobalBallActive\fP"
.br
.ti -1c
.RI "int \fBballCollisions\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BallManager::BallManager (\fBTileSimulator\fP *sim)"

.SS "BallManager::~BallManager ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBBall\fP * BallManager::addBall (Ogre::SceneNode *n, intx, inty, intz, intr)"

.SS "\fBBall\fP * BallManager::addMainBall (Ogre::SceneNode *n, intx, inty, intz, intr)"

.SS "bool BallManager::checkCollisions (btRigidBody *aTile, void *body0, void *body1)"

.SS "void BallManager::clearBalls ()"

.SS "void BallManager::enableGravity ()"

.SS "int BallManager::getNumberBallCollisions ()"

.SS "\fBTileSimulator\fP * BallManager::getSimulator ()"

.SS "bool BallManager::initBallManager ()"

.SS "void BallManager::initMultiplayer (intnPlayers)"

.SS "bool BallManager::isGlobalBall ()"

.SS "bool BallManager::isPlayerBall (intidx)"

.SS "void BallManager::removeBall (\fBBall\fP *rmBall)"

.SS "void BallManager::removeGlobalBall ()"

.SS "void BallManager::removePlayerBall (intidx)"

.SS "void BallManager::setGlobalBall (\fBBall\fP *ball)"

.SS "void BallManager::setPlayerBall (\fBBall\fP *ball, intidx)"

.SH "Member Data Documentation"
.PP 
.SS "int BallManager::ballCollisions\fC [private]\fP"

.SS "std::vector<\fBBall\fP *> BallManager::ballList\fC [private]\fP"

.SS "\fBBall\fP* BallManager::globalBall"

.SS "bool BallManager::globalBallActive\fC [private]\fP"

.SS "std::vector<\fBBall\fP *> BallManager::mainBalls\fC [private]\fP"

.SS "std::vector<\fBBall\fP *> BallManager::playerBalls"

.SS "std::vector<bool> BallManager::playerBallsActive\fC [private]\fP"

.SS "\fBTileSimulator\fP* BallManager::sim\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
