.TH "BaseGame.h" 3 "Tue Mar 11 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseGame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OgreCamera\&.h>\fP
.br
\fC#include <OgreEntity\&.h>\fP
.br
\fC#include <OgreLogManager\&.h>\fP
.br
\fC#include <OgreRoot\&.h>\fP
.br
\fC#include <OgreViewport\&.h>\fP
.br
\fC#include <OgreSceneManager\&.h>\fP
.br
\fC#include <OgreRenderWindow\&.h>\fP
.br
\fC#include <OgreConfigFile\&.h>\fP
.br
\fC#include <OISEvents\&.h>\fP
.br
\fC#include <OISInputManager\&.h>\fP
.br
\fC#include <OISKeyboard\&.h>\fP
.br
\fC#include <OISMouse\&.h>\fP
.br
\fC#include <SdkTrays\&.h>\fP
.br
\fC#include <SdkCameraMan\&.h>\fP
.br
\fC#include <OISMultiTouch\&.h>\fP
.br
\fC#include <macUtils\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseGame\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOGRE_IS_IOS\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OGRE_IS_IOS   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
