.TH "CameraMan" 3 "Thu Mar 13 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraMan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraMan\&.h>\fP
.PP
Inherits SdkCameraMan\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraMan\fP (Ogre::Camera *c)"
.br
.ti -1c
.RI "virtual bool \fBframeRenderingQueued\fP (const Ogre::FrameEvent &evt)"
.br
.ti -1c
.RI "virtual void \fBinjectKeyDown\fP (const OIS::KeyEvent &evt)"
.br
.ti -1c
.RI "virtual void \fBinjectKeyUp\fP (const OIS::KeyEvent &evt)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CameraMan::CameraMan (Ogre::Camera *c)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool CameraMan::frameRenderingQueued (const Ogre::FrameEvent &evt)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void CameraMan::injectKeyDown (const OIS::KeyEvent &evt)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void CameraMan::injectKeyUp (const OIS::KeyEvent &evt)\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
