.TH "config.h" 3 "Tue Mar 11 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP   '\&.libs/'"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'SampleApp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   ''"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '0\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_DLFCN_H   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_MEMORY_H   1"

.SS "#define HAVE_STDINT_H   1"

.SS "#define HAVE_STDLIB_H   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRINGS_H   1"

.SS "#define HAVE_SYS_STAT_H   1"

.SS "#define HAVE_SYS_TYPES_H   1"

.SS "#define HAVE_UNISTD_H   1"

.SS "#define LT_OBJDIR   '\&.libs/'"

.SS "#define PACKAGE   'SampleApp'"

.SS "#define PACKAGE_BUGREPORT   ''"

.SS "#define PACKAGE_NAME   ''"

.SS "#define PACKAGE_STRING   ''"

.SS "#define PACKAGE_TARNAME   ''"

.SS "#define PACKAGE_URL   ''"

.SS "#define PACKAGE_VERSION   ''"

.SS "#define STDC_HEADERS   1"

.SS "#define VERSION   '0\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
