.TH "ConnectionInfo" 3 "Fri Mar 21 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NetManager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IPaddress \fBaddress\fP"
.br
.RI "\fIThis connection's IPaddress\&. \fP"
.ti -1c
.RI "\fBProtocol\fP \fBprotocols\fP"
.br
.RI "\fIAssociated protocols\&. \fP"
.ti -1c
.RI "int \fBtcpSocketIdx\fP"
.br
.RI "\fIIndex into the tcpSocket vector\&. \fP"
.ti -1c
.RI "int \fBudpSocketIdx\fP"
.br
.RI "\fIIndex into the udpSocket vector\&. \fP"
.ti -1c
.RI "int \fBtcpDataIdx\fP"
.br
.RI "\fIIndex into the tcpClientData vector\&. \fP"
.ti -1c
.RI "int \fBudpDataIdx\fP"
.br
.RI "\fIIndex into the udpClientData vector\&. \fP"
.ti -1c
.RI "int \fBudpChannel\fP"
.br
.RI "\fIThe associated UDP channel\&. \fP"
.ti -1c
.RI "int \fBclientIdx\fP"
.br
.RI "\fIIndex into the tcpClients vector\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Internal state information packaging\&. 
.SH "Member Data Documentation"
.PP 
.SS "IPaddress ConnectionInfo::address"

.PP
This connection's IPaddress\&. 
.SS "int ConnectionInfo::clientIdx"

.PP
Index into the tcpClients vector\&. 
.SS "\fBProtocol\fP ConnectionInfo::protocols"

.PP
Associated protocols\&. 
.SS "int ConnectionInfo::tcpDataIdx"

.PP
Index into the tcpClientData vector\&. 
.SS "int ConnectionInfo::tcpSocketIdx"

.PP
Index into the tcpSocket vector\&. 
.SS "int ConnectionInfo::udpChannel"

.PP
The associated UDP channel\&. 
.SS "int ConnectionInfo::udpDataIdx"

.PP
Index into the udpClientData vector\&. 
.SS "int ConnectionInfo::udpSocketIdx"

.PP
Index into the udpSocket vector\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
