.TH "NetManager::ConnectionInfo" 3 "Tue Mar 11 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetManager::ConnectionInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBtcpSocketIdx\fP"
.br
.ti -1c
.RI "short \fBudpSocketIdx\fP"
.br
.ti -1c
.RI "short \fBtcpClientIdx\fP"
.br
.ti -1c
.RI "short \fBudpClientIdx\fP"
.br
.ti -1c
.RI "short \fBtcpDataIdx\fP"
.br
.ti -1c
.RI "short \fBudpDataIdx\fP"
.br
.ti -1c
.RI "short \fBudpChannel\fP"
.br
.ti -1c
.RI "\fBProtocol\fP \fBprotocols\fP"
.br
.ti -1c
.RI "IPaddress \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal state information packaging\&. 
.SH "Member Data Documentation"
.PP 
.SS "IPaddress NetManager::ConnectionInfo::address"

.SS "\fBProtocol\fP NetManager::ConnectionInfo::protocols"

.SS "short NetManager::ConnectionInfo::tcpClientIdx"

.SS "short NetManager::ConnectionInfo::tcpDataIdx"

.SS "short NetManager::ConnectionInfo::tcpSocketIdx"

.SS "short NetManager::ConnectionInfo::udpChannel"

.SS "short NetManager::ConnectionInfo::udpClientIdx"

.SS "short NetManager::ConnectionInfo::udpDataIdx"

.SS "short NetManager::ConnectionInfo::udpSocketIdx"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
