.TH "NetManager.cpp" 3 "Fri Mar 21 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetManager.cpp \- 
.PP
Networking wrapper for SDL_net created for OGRE engine use in CS 354R at the University of Texas at Austin, taught by Don Fussell in Spring 2014\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'NetManager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOCALHOST_NBO\fP   16777343"
.br
.in -1c
.SH "Detailed Description"
.PP 
Networking wrapper for SDL_net created for OGRE engine use in CS 354R at the University of Texas at Austin, taught by Don Fussell in Spring 2014\&. 

\fBDate:\fP
.RS 4
March 7, 2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
Wade Burch (nolnoch@cs.utexas.edu)
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define LOCALHOST_NBO   16777343"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
