.TH "NetTestClient.cpp" 3 "Thu Mar 13 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetTestClient.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'NetManager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
