.TH "OgreMotionState" 3 "Tue Mar 11 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OgreMotionState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OgreMotionState\&.h>\fP
.PP
Inherits btMotionState\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOgreMotionState\fP (btTransform newposition, Ogre::SceneNode *object)"
.br
.ti -1c
.RI "void \fBgetWorldTransform\fP (btTransform &worldTrans) const "
.br
.ti -1c
.RI "void \fBsetWorldTransform\fP (const btTransform &worldTrans)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Ogre::SceneNode * \fBogreObject\fP"
.br
.ti -1c
.RI "btTransform \fBposition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OgreMotionState::OgreMotionState (btTransformnewposition, Ogre::SceneNode *object)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void OgreMotionState::getWorldTransform (btTransform &worldTrans) const\fC [inline]\fP"

.SS "void OgreMotionState::setWorldTransform (const btTransform &worldTrans)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Ogre::SceneNode* OgreMotionState::ogreObject\fC [protected]\fP"

.SS "btTransform OgreMotionState::position\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
