.TH "PlayerData" 3 "Fri Mar 21 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileGame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBhost\fP"
.br
.ti -1c
.RI "Ogre::Vector3 \fBnewDir\fP"
.br
.ti -1c
.RI "Ogre::Vector3 \fBnewPos\fP"
.br
.ti -1c
.RI "Ogre::Vector3 \fBshotDir\fP"
.br
.ti -1c
.RI "double \fBshotForce\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Uint32 PlayerData::host"

.SS "Ogre::Vector3 PlayerData::newDir"

.SS "Ogre::Vector3 PlayerData::newPos"

.SS "Ogre::Vector3 PlayerData::shotDir"

.SS "double PlayerData::shotForce"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
