.TH "PlayerOldData" 3 "Wed Apr 2 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerOldData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileGame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Ogre::Quaternion \fBoldDir\fP"
.br
.ti -1c
.RI "Ogre::Vector3 \fBoldPos\fP"
.br
.ti -1c
.RI "double \fBdelta\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double PlayerOldData::delta"

.SS "Ogre::Quaternion PlayerOldData::oldDir"

.SS "Ogre::Vector3 PlayerOldData::oldPos"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
