.TH "SoundManager.cpp" 3 "Wed Apr 2 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SoundManager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchannelDoneWrapper\fP (int)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void channelDoneWrapper (intchannel)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
