.TH "Sound" 3 "Wed Apr 2 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SoundManager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Ogre::Vector3 \fBsoundPosition\fP"
.br
.ti -1c
.RI "Mix_Chunk * \fBchunk\fP"
.br
.ti -1c
.RI "int \fBdistance\fP"
.br
.ti -1c
.RI "int \fBchannel\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool Sound::active"

.SS "int Sound::channel"

.SS "Mix_Chunk* Sound::chunk"

.SS "int Sound::distance"

.SS "Ogre::Vector3 Sound::soundPosition"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
