.TH "TileGame.h" 3 "Wed Mar 12 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileGame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BaseGame\&.h'\fP
.br
\fC#include 'BallManager\&.h'\fP
.br
\fC#include 'SoundManager\&.h'\fP
.br
\fC#include 'NetManager\&.h'\fP
.br
\fC#include 'CameraMan\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTileGame\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBWALL_SIZE\fP = 2400"
.br
.ti -1c
.RI "static const int \fBPLANE_DIST\fP = \fBWALL_SIZE\fP / 2"
.br
.ti -1c
.RI "static const int \fBNUM_TILES_ROW\fP = 5"
.br
.ti -1c
.RI "static const int \fBNUM_TILES_WALL\fP = \fBNUM_TILES_ROW\fP * \fBNUM_TILES_ROW\fP"
.br
.ti -1c
.RI "static const int \fBTILE_WIDTH\fP = \fBWALL_SIZE\fP / \fBNUM_TILES_ROW\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int NUM_TILES_ROW = 5\fC [static]\fP"

.SS "const int NUM_TILES_WALL = \fBNUM_TILES_ROW\fP * \fBNUM_TILES_ROW\fP\fC [static]\fP"

.SS "const int PLANE_DIST = \fBWALL_SIZE\fP / 2\fC [static]\fP"

.SS "const int TILE_WIDTH = \fBWALL_SIZE\fP / \fBNUM_TILES_ROW\fP\fC [static]\fP"

.SS "const int WALL_SIZE = 2400\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
