.TH "TileSimulator.h" 3 "Wed Mar 12 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileSimulator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <bullet/btBulletDynamicsCommon\&.h>\fP
.br
\fC#include <OgreSceneManager\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Simulator\&.h'\fP
.br
\fC#include 'BallManager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTileSimulator\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static btRigidBody * \fBactivetile\fP"
.br
.ti -1c
.RI "static \fBBallManager\fP * \fBtileBallMgr\fP"
.br
.ti -1c
.RI "static bool \fBtargethit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "btRigidBody* activetile\fC [static]\fP"

.SS "bool targethit\fC [static]\fP"

.SS "\fBBallManager\fP* tileBallMgr\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
