.TH "TileGame.cpp" 3 "Thu Mar 13 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileGame.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TileGame\&.h'\fP
.br
\fC#include <macUtils\&.h>\fP
.br
\fC#include 'AppDelegate\&.h'\fP
.br
\fC#include 'windows\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "INT WINAPI \fBWinMain\fP (HINSTANCE hInst, HINSTANCE, LPSTR strCmdLine, INT)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WIN32_LEAN_AND_MEAN"

.SH "Function Documentation"
.PP 
.SS "INT WINAPI WinMain (HINSTANCEhInst, HINSTANCE, LPSTRstrCmdLine, INT)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
