.TH "TileSimulator" 3 "Tue Mar 11 2014" "OGRE Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileSimulator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileSimulator\&.h>\fP
.PP
Inherits \fBSimulator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTileSimulator\fP ()"
.br
.ti -1c
.RI "virtual \fB~TileSimulator\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitSimulator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBsimulateStep\fP (double delay)"
.br
.ti -1c
.RI "virtual btRigidBody * \fBaddBallShape\fP (Ogre::SceneNode *n, int r)"
.br
.ti -1c
.RI "btRigidBody * \fBaddTile\fP (Ogre::SceneNode *n, int x, int y, int z)"
.br
.ti -1c
.RI "void \fBsetBallManager\fP (\fBBallManager\fP *bM)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBtileCallback\fP (btManifoldPoint &cp, void *body0, void *body1)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::deque< btRigidBody * > \fBtiles\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TileSimulator::TileSimulator ()"

.SS "TileSimulator::~TileSimulator ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "btRigidBody * TileSimulator::addBallShape (Ogre::SceneNode *n, intr)\fC [virtual]\fP"

.SS "btRigidBody * TileSimulator::addTile (Ogre::SceneNode *n, intx, inty, intz)"

.SS "void TileSimulator::initSimulator ()\fC [virtual]\fP"

.PP
Reimplemented from \fBSimulator\fP\&.
.SS "void TileSimulator::setBallManager (\fBBallManager\fP *bM)"

.SS "bool TileSimulator::simulateStep (doubledelay)\fC [virtual]\fP"

.PP
Reimplemented from \fBSimulator\fP\&.
.SS "bool TileSimulator::tileCallback (btManifoldPoint &cp, void *body0, void *body1)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::deque<btRigidBody *> TileSimulator::tiles\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for OGRE Game from the source code\&.
